### ISSUE TITLE
Possible race condition in CBUF

### ISSUE THREAD

**Issue by Boldie** [dhylands/libopencm3-usb-serial#1]
Hi,

the following statement may produce a race condition especially in interrupt context:

`
#define CBUF_Push(cbuf, elem) (cbuf.m_entry)[ cbuf.m_put_idx++ & CBUF_Mask(cbuf)] = (elem)
`

If you push something from main, and if the interrupt happens before the elem is assigned but after cbuf.m_put_idx++  is incremented, a wrong byte will be read. Found this just by inspecting your code while looking for usb usage in interrupt context. 

The following code will fix this issue:
`
#define CBUF_Push(cbuf, elem) (cbuf.m_entry)[ cbuf.m_put_idx & CBUF_Mask(cbuf)] = (elem); ++cbuf.m_put_idx
`

There may be some more similar issues within your CBUF code.

**Comment by dhylands** [comment]
Indeed. This was fixed in the CBUF.h in my main repository:
https://github.com/dhylands/projects/commit/2a5de1ba8ddb1c315600079d8fc75febed61c27e
but I neglected to carry the fix forward.

Thanks for the report. I'll get that fixed.

**Comment by dhylands** [comment]
Fixed by https://github.com/dhylands/libopencm3-usb-serial/commit/da8ff1f56b7a14843934b8f33845cc1622667192
